name: setup
description: Setup Java and Gradle
runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
