name: checkout-setup
description: Checkout source code and setup Java and Gradle
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
