name: First Interaction
# https://github.com/marketplace/actions/first-interaction

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1.2.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >
          Hi!
          
          
          First of all, thank you for opening your first issue. Elementary, we appreciate all feedback that helps us continue improving this plugin.
          
          
          As this is a [community project](https://github.com/sonatype-nexus-community/scan-gradle-plugin#the-fine-print) we can't commit to official due dates for reviews and developing, but we're definitely committed to delivering services, integrations and plugins of top quality.
          
          
          So please be patient, we will review your issue and get back to you as soon as we can!
          
          
          
          Regards,
          
          Sherlock Trunks 🐘
        pr-message: >
          Hi!
          
          
          First of all, thank you for opening your first pull-request. Elementary, we appreciate all submissions that helps us continue improving this plugin.
          
          
          Please take a look to our [contributing guidelines](https://github.com/sonatype-nexus-community/scan-gradle-plugin/blob/main/.github/CONTRIBUTING.md) and make sure all requirements are fulfilled.
          
          
          As this is a [community project](https://github.com/sonatype-nexus-community/scan-gradle-plugin#the-fine-print) we can't commit to official due dates for reviews and developing, but we're definitely committed to delivering services, integrations and plugins of top quality.
          
          
          So please be patient, we will review your pull-request and get back to you as soon as we can!
          
          
          
          Regards,
          
          Sherlock Trunks 🐘
